#!/usr/bin/env bash

DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
. "$DIR/script/globals"
. "$DIR/script/functions"


set_gpg_home
flush_passphrase_cache
clear_gpg_agent_files
kill_agent
${SSH_ADD_BIN} -D