#!/usr/bin/env bash

DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
. "$DIR/script/globals"
. "$DIR/script/functions"

KEY_NAME=$1
HOURS=$2
CLEAR=$3

if [ -z $KEY_NAME ]; then
   echo "ERROR! load requires a key name!"
fi

if [ -z $HOURS ]; then
  HOURS=1
fi

function check_dependencies {
    [ -z "${SSH_AGENT_BIN}" ] && echo "No ssh-agent bin found, exiting." && exit 1
    [ -z "${SSH_ADD_BIN}" ] && echo "No ssh-add bin found, exiting." && exit 1
}

function load_key {

    if [ "$CLEAR" = "--clear" ]; then
        ${SSH_ADD_BIN} -D
    fi
    ${SSH_ADD_BIN} -t ${HOURS}H $DIR/$1
}

function load_keys {
    SSH_KEYS=`${GREP_BIN} -rl 'BEGIN .* PRIVATE KEY' ${SSH_KEY_DIR}`

    # No private keys found in directory
    if [ -z ${SSH_KEYS} ]; then
        encrypt_private_keys
        print_separator
        echo "ERROR! No ssh keys found, exiting." && exit 1
    fi

    for key in $SSH_KEYS
    do
	    load_key $key
    done
}

function load {
    if [ "$KEY_NAME" = "--all" ]; then
        load_keys
    else
        load_key $SSH_KEY_DIR/$KEY_NAME
    fi
    print_separator
}

if is_encrypted; then
    check_dependencies
    set_gpg_home
    decrypt_private_keys
    flush_passphrase_cache
    untar
    load
    encrypt_private_keys
    clear_gpg_agent_files
    kill_agent
else
    echo "ERROR! Cannot load unencrypted keys! Run: \"sh encrypt\" first";
fi