#!/usr/bin/env bash

# Credentials
KEY_OWNER_NAME="<Your masterkey identifier here>" # Change this to your GPG key owner name or email

# Binaries
GPG_BIN=`which gpg`
SSH_AGENT_BIN=`which ssh-agent`
SSH_ADD_BIN=`which ssh-add`
TAR_BIN=`which tar`
TOUCH_BIN=`which touch`
MV_BIN=`which mv`
CP_BIN=`which cp`
UNLINK_BIN=`which unlink`
RM_BIN=`which rm`
MKDIR_BIN=`which mkdir`
CHMOD_BIN=`which chmod`
HEAD_BIN=`which head`
GREP_BIN=`which grep`

# If we couldn't find GPG then try GPG2
if [ -z "${GPG_BIN}" ]; then
    GPG_BIN=`which gpg2`
fi

# Folders / Files / Key names and locations
SSH_KEY_DIR="ssh"
SSH_FULL_KEY_DIR="sshfull"
GPG_HOME_DIR="$DIR/masterkey"
GPG_AGENT_CONFIG_FILE="$DIR/masterkey/gpg-agent.conf"

# Tar names
SSH_KEY_TAR=${SSH_KEY_DIR}.tar.gz
SSH_FULL_KEY_TAR=${SSH_FULL_KEY_DIR}.tar.gz

# Encrypted files
ENCRYPTED_KEYS_FILE=${SSH_KEY_TAR}.gpg
ENCRYPTED_FULL_KEYS_FILE=${SSH_FULL_KEY_TAR}.gpg

# GPG version
GPG_VERSION=`${GPG_BIN} --version | ${GREP_BIN} -Eo -m 1 "[0-9]" | ${HEAD_BIN} -1`